LBLK-16: New member added
labyes24/lab-links pull request #4
Opened 2024-05-22 18:39 UTC by Villa-Nova

2024-05-22 18:47 UTC, ThalytaRangel requested changes
Os dados da Flávia estão corretos. 
@Villa-Nova Você poderia retirar os dados do Hofs que estão duplicados, por gentileza? 
Só manter a ordem alfabética. 
Assim aproveitamos essa PR para fazer o ajuste.

2024-05-22 19:45 UTC, Villa-Nova commented
@ThalytaRangel Os dados duplicados já foram removidos

2024-05-22 20:38 UTC, ThalytaRangel approved these changes

2024-05-23 16:02 UTC, dam450 approved these changes

2024-05-27 18:20 UTC, merged